#
# MySQL Dockerfile
#
# https://github.com/dockerfile/mysql
#

# Pull base image.
FROM sparkchain/ubuntu_python_jdk8_nodejs:1.0

RUN groupadd -r mysql && useradd -r -g mysql mysql
# Install MySQL.
RUN \
  apt-get update && \
  mkdir -p /var/lib/mysql /var/run/mysqld   &&\
  chown -R mysql:mysql /var/lib/mysql /var/run/mysqld 	&&\
 # chown root:mysql /var/run/mysqld  && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server && \
  rm -rf /var/lib/apt/lists/* && \
  sed -i 's/^\(bind-address\s.*\)/# \1/' /etc/mysql/my.cnf && \
  sed -i 's/^\(log_error\s.*\)/# \1/' /etc/mysql/my.cnf && \
  echo "mysqld_safe &" > /tmp/config && \
  echo "mysqladmin --silent --wait=30 ping || exit 1" >> /tmp/config && \
  echo "mysql -e 'GRANT ALL PRIVILEGES ON *.* TO \"root\"@\"%\" WITH GRANT OPTION;'" >> /tmp/config && \
  bash /tmp/config && \
  rm -f /tmp/config

# Define mountable directories.
VOLUME ["/etc/mysql", "/var/lib/mysql"]

# Define working directory.
WORKDIR /data

# Define default command.
CMD ["mysqld_safe"]

# Expose ports.
EXPOSE 3306

#docker build -t  sparkchain/ubuntu_python_jdk8_nodejs_mysql:1.0  D:\code\github\k8s-new\13dockerfile\06mysql\ -f Dockerfile
